runtime: php83

env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: ${APP_KEY}
  MAPS_API_KEY: ${MAPS_API_KEY}
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PASSWORD: ${REDIS_PASSWORD}

handlers:
  # Serve static assets with appropriate cache headers
  - url: /build/(.*)
    static_files: public/build/\1
    upload: public/build/(.*)
    secure: always
    expiration: "30d"
    http_headers:
      Cache-Control: "public, max-age=2592000"
      X-Content-Type-Options: "nosniff"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
      X-XSS-Protection: "1; mode=block"
      X-Frame-Options: "SAMEORIGIN"
      Referrer-Policy: "strict-origin-when-cross-origin"

  # Serve public assets
  - url: /(.+\.(ico|jpg|jpeg|png|gif|svg|js|css|woff|woff2|ttf|eot))$
    static_files: public/\1
    upload: public/(.+\.(ico|jpg|jpeg|png|gif|svg|js|css|woff|woff2|ttf|eot))$
    secure: always
    expiration: "30d"
    http_headers:
      Cache-Control: "public, max-age=2592000"
      X-Content-Type-Options: "nosniff"

  # Serve the index.php file
  - url: /.*
    script: auto
    secure: always

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

vpc_access_connector:
  name: projects/${PROJECT_ID}/locations/${REGION}/connectors/redis-connector

inbound_services:
- warmup
