version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: earthvr-custom-tours:latest
    container_name: earthvr-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - MAPS_API_KEY=${MAPS_API_KEY}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - redis
    networks:
      - earthvr-network

  web:
    image: nginx:alpine
    container_name: earthvr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - earthvr-network

  redis:
    image: redis:alpine
    container_name: earthvr-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-secret}
    volumes:
      - redis-data:/data
    networks:
      - earthvr-network

networks:
  earthvr-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
